spring.application.name=studServis
server.port=8081

#spring.application.name=studentski-servis

# MySQL Konfiguracija
spring.datasource.url=jdbc:mysql://localhost:3306/studentski_servis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate pode\u0161avanja
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
